<?php

namespace Tests;


use App\Models\Label;
use App\Models\Service;
use App\Models\Task;
use App\Models\TodoList;
use App\Models\User;
use Illuminate\Foundation\Testing\TestCase as BaseTestCase;
use Laravel\Sanctum\Sanctum;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication;


    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->withoutExceptionHandling();
    }

    public function authenticate()

    {
        $user = User::factory()->make();
        $this->actingAs($user);
    }

    public function createTodoList($args)
    {
        return TodoList::factory()->count(5)->create($args);
    }

    public function createTaskList($args)
    {
        return Task::factory()->count(10)->create($args);
    }

    public function createUser()
    {
        return User::factory()->create();
    }

    public function sanctumAuthenticate()
    {
        $user = $this->createUser();
        Sanctum::actingAs($user);
        return $user;
    }

    public function createLabel($args)
    {
        return Label::factory()->create($args);
    }

    public function createService($args)
    {
        return Service::factory()->create($args);
    }


}
