<?php

namespace Tests\Feature;

use App\Models\Bevarage;
use App\Models\User;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class BeverageTest extends TestCase
{

    use DatabaseMigrations;

    protected $beverage;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->beverage = Bevarage::factory()->create();

    }

    /** @test */
    public function a_user_can_visit_a_beverage_page_and_see_beverage()
    {
//        $beverage = Bevarage::factory()->make();
//        $beverage = Bevarage::factory()->create();
        //user will go to a url
        $response = $this->get('/beverage');
        $response->assertSee($this->beverage->name);
        $response->assertStatus(200);
        //assert status
    }

    /** @test */
    public function _a_user_can_visit_single_beverage_page()
    {
//       $beverage = Bevarage::factory()->create();
        $response = $this->get('/beverage/' . $this->beverage->id);
        $response->assertStatus(200);
    }

    /** @test */
    public function a_logged_iin_user_can_buy_beverage()
    {
        //logged in user
//        $user=User::factory()->make();
//        $this->actingAs($user);
        $this->authenticate();
        //post a data
        $data = ['beverageId' => $this->beverage->id, 'price' => 200];
        $response = $this->post('/beverage/buy', $data);
        //assert in database
        $this->assertDatabaseHas('purchases', $data);
        //status
        $response->assertStatus(201);

    }
}
