<?php

namespace Tests\Feature\Auth;

;

use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class LoginTest extends TestCase
{
    /**
     * A basic feature test example.
     *
     * @return void
     */
    use refreshDatabase;
    protected $user;
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->user=$this->createUser();
    }

    public function test_user_can_login_with_email_and_password()
    {
        $response = $this->postJson(route('user.login'), ['email'=>$this->user->email,'password'=>'password']);
        $this->assertArrayHasKey('token', $response->json());
    }

    public function test_if_user_email_is_not_available_then_it_return_error()
    {


        $response = $this->postJson(route('user.login'), ['email' => 'ahmedjubayer541@gmail.com', 'password' => 'password1'])->assertUnauthorized();

    }

    public function test_if_user_password_is_not_available_then_it_return_error()
    {
        $user = User::factory()->create();
        $response = $this->postJson(route('user.login'), ['email' => 'ahmedjubayer541@gmail.com', 'password' => 'password76'])->assertUnauthorized();

    }
}
