<?php

namespace Tests\Unit;

use App\Models\Task;
use App\Models\TodoList;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class TaskTest extends TestCase
{

    use refreshDatabase;

    protected $lists;
    protected $tasks;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->lists = $this->createTodoList('');
        $this->tasks = $this->createTaskList(['todolistId' => $this->lists[0]['id']]);
    }

    public function test_a_todo_list_can_has_many_relationships()
    {

        //$this->assertInstanceOf(Collection::class,$this->lists[0]->tasks);

        $this->assertInstanceOf(TodoList::class, $this->tasks[0]->todolist);

    }
}
