<?php

namespace Tests\Unit;

use App\Models\Task;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class TodoListTest extends TestCase
{
    /**
     * A basic unit test example.
     *
     * @return void
     */

    use refreshDatabase;

    protected $lists;
    protected $tasks;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->lists = $this->createTodoList('');
        $this->tasks = $this->createTaskList(['todolistId' => $this->lists[0]['id']]);
    }

    public function test_a_todo_list_can_has_many_relationships()
    {

        $this->assertInstanceOf(Collection::class, $this->lists[0]->tasks);
        $this->assertInstanceOf(Task::class, $this->lists[0]->tasks->first());

    }

    public function test_if_todo_list_is_deleted_then_all_its_tasks_will_be_deleted()
    {
        $this->lists[0]->delete();
        $task = $this->createTaskList(['todolistId' => $this->lists[1]['id']]);

        $this->assertDatabaseMissing('todo_lists', ['id' => $this->lists[0]['id']]);
        $this->assertDatabaseMissing('tasks', ['id' => $this->tasks[0]['id']]);
        $this->assertDatabaseHas('tasks', ['id' => $task[9]['id']]);
    }


}
